### PR TITLE
p0: add new tests + upgrade dependencies

### PR DESCRIPTION
**Pull request by skyzh**
also upgrade to C++ 23 so that we can use std::backtrace

### CODE REVIEW

**Comment by skyzh** [comment]
need to revert to C++23 change 🤣

**Review by yliang412 — COMMENTED** [review]
Does changing to C++23 break other part of the codebase?

**Comment by xzhseh** [comment]
Should we also manually add `-std=c++23` flag in `CMakeLists.txt`🤔

**Comment by skyzh** [comment]
decided to drop C++23 for this semester and bumped several dependencies, PTAL again, thanks! @yliang412

**Review by yliang412 — APPROVED** [review]
Great work!

**Pull request merged**
