### PR TITLE
chore(style): enforce `modernize-use-trailing-return-type`

### PR DESCRIPTION
**Pull request by skyzh**
As title. We enforce this rule except in `test` and `primer` directory.

### CODE REVIEW

**Comment by skyzh** [comment]
Also add `make fix-clang-tidy` to automatically fix clang tidy warnings.

**Comment by skyzh** [comment]
@amstqq I'd like to apply this rule starting p0. What do you think?

**Comment by skyzh** [comment]
Postpone merging until project 1

**Comment by skyzh** [comment]
... or not postpone?

**Comment by skyzh** [comment]
This rule is solely disabled for p0, so we can get it merged now.

**Review by lmwnshn — APPROVED** [review]
LGTM (please doublecheck that it will not break P0 on the autograder; the autograder is a zipfile that needs manual updating)

**Comment by skyzh** [comment]
Verified to work with the current refsol.

**Comment by skyzh** [comment]
Also it won't affect current students as long as they don't modify other files.

**Pull request merged**
