### PR TITLE
refactor(container): separate memory and disk hash table

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

Still see if CI could pass...

### CODE REVIEW

**Comment by skyzh** [comment]
I didn't sync extendible_hash_table_test.cpp (which needs adding `DISABLED_` prefix to all test cases). May do later. Also need to revisit what we want to expose to students for `extendible_hash_table.h`.

**Comment by skyzh** [comment]
For reviewers: the only new files in this PR is src/container/hash/extendible_hash_table.cpp and src/include/container/hash/extendible_hash_table.h. All other files are just about renaming, but git apparently doesn't recognize such renames.

**Comment by skyzh** [comment]
Ready for review, needs approval from @timlee0119

**Review by timlee0119 — APPROVED** [review]
LGTM!

**Pull request merged**
