### PR TITLE
Fall 2024 Project 3

### PR DESCRIPTION
**Pull request by xx01cyx**

### CODE REVIEW

**Comment by connortsui20** [comment]
Can we potentially separate the `.slt` files into a separate PR?

**Comment by xx01cyx** [comment]
> Can we potentially separate the `.slt` files into a separate PR?

Okay. Will update.

**Comment by xx01cyx** [comment]
> Can we potentially separate the .slt files into a separate PR?

See #767

**Review by prashanthduvvada — APPROVED** [review]
LGTM

**Pull request merged**
