### PR TITLE
Buffer pool

### PR DESCRIPTION
**Pull request by duynl58**

### CODE REVIEW

**Comment by lmwnshn** [comment]
@duynl58 Could you please delete your branch?

Please don't publish solutions to projects.
You can make a private copy of the repository and do what you want there.
Help keep this codebase open and freely accessible to everyone!

**Comment by duynl58** [comment]
@lmwnshn sorry for spamming. It was my mistake creating the PR. Sure, I will make mine private repository.

**Comment by lmwnshn** [comment]
Thanks! Trying to see if GitHub will delete the PR so that students can't find it so easily later this August. I don't think either of us have the power to do that, unfortunately.

Have fun! :)

**Comment by duynl58** [comment]
From this site:

https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

I believe that the only way is to contact the GitHub staff. I would not a sensible person to do so, please help me contact them on your own. Thanks!

**Pull request closed without merging**
