### PR TITLE
feat: update LockRequestQueue::request_queue_ & fix typos & ensure format consistency

### PR DESCRIPTION
**Pull request by xzhseh**
This PR mainly does three things in general.
1. According to the unofficial discord conversation history in 2022 P4-2022, 
by `@ moraceae` & `@ chichi` & `@ francischeng`, which indicated it'd be hard to avoid memory leak if using raw pointer instead of smart pointer, and it really is.
Thus, this PR updates the raw pointer inside `LockRequestQueue::request_queue_` to `std::shared_ptr`, which makes life much easier (If by any chance the students just follow this paradigm and structure when programming through `LockManager`..)
3. Also according to the suggestion from `@ moraceae` & `@ chichi`, I updated the [Lock Note] for `lock upgrade` and `book keeping` sections, to give students a hint and also remind the students about the correct logic. (I didn't find any reference about this through notes, lectures, so I added it there)
4. I looked through the overall repository and fix several typos, also ensured the code format's consistency.

### CODE REVIEW

**Comment by xzhseh** [comment]
But if the 23 Fall version is turning into MVCC, then the added comments may be of no use🤪

**Review by skyzh — APPROVED** [review]
Thanks for the fixes!

**Comment by skyzh** [comment]
... and there is a merge conflict. Would you please help fix that? Otherwise I'll fix and merge on the weekends.

**Comment by xzhseh** [comment]
> ... and there is a merge conflict. Would you please help fix that? Otherwise I'll fix and merge on the weekends.

Sure, I'll fix that later🥰

**Pull request merged**
