### PR TITLE
P0 Starter Code

### PR DESCRIPTION
**Pull request by prashanthduvvada**
Starter Code for P0.

### CODE REVIEW

**Review by cjtsui — APPROVED** [review]
It would be good if the doc comments had proper capitalization and punctuation, but other than that lgtm

**Review by connortsui20 — APPROVED** [review]
whoops wrong account

**Comment by tre3p** [comment]
@prashanthduvvada maybe you can also add examples of cardinality calculations on the primer page? Cause you have examples of how data is laid out, but not how cardinality is calculated then based on this data. Thx in advance!

**Comment by prashanthduvvada** [comment]
Okay ..that should fix most confusions. I was thinking about the same.

**Pull request merged**
