### PR TITLE
chore(bpm): throw when unimplemented

### PR DESCRIPTION
**Pull request by skyzh**
Signed-off-by: Alex Chi <iskyzh@gmail.com>

### CODE REVIEW

**Comment by timlee0119** [comment]
Should we ask students to pull this?

**Review by timlee0119 — COMMENTED** [review]
LGTM

**Comment by skyzh** [comment]
We don't need to. This doesn't affect p1 very much. I think the real problem will start at p2, where we might have updated a lot of code and students will need to do a merge.

**Comment by skyzh** [comment]
Can you help approve instead of comment? 🤣 We have this merging rule 🥵 Thanks!

**Review by timlee0119 — APPROVED** [review]

**Comment by timlee0119** [comment]
sorry my bad 🥵

**Pull request merged**
